import type { Product, Category } from '@/types'

// ─── Categorías ───────────────────────────────────────────────────────────────

export const mockCategories: Category[] = [
  { id: 'cat-la', name: 'Lácteos',          slug: 'lacteos',          order: 1 },
  { id: 'cat-ab', name: 'Despensa',          slug: 'despensa',         order: 2 },
  { id: 'cat-fv', name: 'Frutas y Verduras', slug: 'frutas-verduras',  order: 3 },
  { id: 'cat-ca', name: 'Carnes',            slug: 'carnes',           order: 4 },
  { id: 'cat-as', name: 'Aseo',              slug: 'aseo',             order: 5 },
  { id: 'cat-pa', name: 'Panadería',         slug: 'panaderia',        order: 6 },
  { id: 'cat-be', name: 'Bebidas',           slug: 'bebidas',          order: 7 },
]

// ─── Productos ────────────────────────────────────────────────────────────────
// TODO: reemplazar imageUrl con imágenes WebP 400×400 reales de Leche y Miel
//       < 30KB por imagen. Convenio: /assets/products/<id>.webp

export const mockProducts: Product[] = [
  // ── Lácteos ──────────────────────────────────────────────────────────────
  {
    id: 'leche-entera-1l',
    name: 'Leche entera pasteurizada 1L',
    name_display: 'Leche Entera',
    name_legal: 'Leche entera pasteurizada UHT 1 litro',
    price: 4500,
    unit: '1 L',
    imageUrl: 'https://placehold.co/400x400/0a7e3a/white?text=Leche.webp',
    categoryId: 'cat-la',
    inStock: true,
    is_variable_weight: false,
    currency: 'COP',
  },
  {
    id: 'queso-campesino-250g',
    name: 'Queso campesino fresco 250g',
    name_display: 'Queso Campesino',
    name_legal: 'Queso campesino fresco artesanal 250g',
    price: 7500,
    unit: '250 g',
    imageUrl: 'https://placehold.co/400x400/0a7e3a/white?text=Queso.webp',
    categoryId: 'cat-la',
    inStock: true,
    is_variable_weight: false,
    currency: 'COP',
    badge: 'Local',
  },
  {
    id: 'mantequilla-250g',
    name: 'Mantequilla con sal 250g',
    name_display: 'Mantequilla',
    name_legal: 'Mantequilla pasteurizada con sal 250g',
    price: 6800,
    unit: '250 g',
    imageUrl: 'https://placehold.co/400x400/0a7e3a/white?text=Mantequilla.webp',
    categoryId: 'cat-la',
    inStock: false,  // Agotado — valida US-3 / AC-3
    is_variable_weight: false,
    currency: 'COP',
  },
  {
    id: 'yogurt-natural-1l',
    name: 'Yogurt natural 1L',
    name_display: 'Yogurt Natural',
    name_legal: 'Yogurt natural entero sin azúcar 1 litro',
    price: 8200,
    unit: '1 L',
    imageUrl: 'https://placehold.co/400x400/0a7e3a/white?text=Yogurt.webp',
    categoryId: 'cat-la',
    inStock: true,
    is_variable_weight: false,
    currency: 'COP',
  },

  // ── Carnes ───────────────────────────────────────────────────────────────
  {
    id: 'pollo-entero',
    name: 'Pollo entero fresco',
    name_display: 'Pollo Entero',
    name_legal: 'Pollo entero fresco sin vísceras por unidad',
    price: 22000,
    unit: 'unidad',
    imageUrl: 'https://placehold.co/400x400/0a7e3a/white?text=Pollo.webp',
    categoryId: 'cat-ca',
    inStock: true,
    is_variable_weight: false,
    currency: 'COP',
  },
  {
    id: 'carne-molida-500g',
    name: 'Carne de res molida 500g',
    name_display: 'Carne Molida',
    name_legal: 'Carne bovina molida fresca 500g',
    price: 14500,
    unit: '500 g',
    imageUrl: 'https://placehold.co/400x400/0a7e3a/white?text=Carne+Molida.webp',
    categoryId: 'cat-ca',
    inStock: true,
    is_variable_weight: false,
    currency: 'COP',
    badge: 'Oferta',
  },
  {
    id: 'chorizo-250g',
    name: 'Chorizo casero 250g',
    name_display: 'Chorizo',
    name_legal: 'Chorizo de cerdo artesanal 250g',
    price: 9000,
    unit: '250 g',
    imageUrl: 'https://placehold.co/400x400/0a7e3a/white?text=Chorizo.webp',
    categoryId: 'cat-ca',
    inStock: true,
    is_variable_weight: false,
    currency: 'COP',
  },

  // ── Frutas y Verduras ─────────────────────────────────────────────────────
  {
    id: 'platano-verde',
    name: 'Plátano verde',
    name_display: 'Plátano Verde',
    name_legal: 'Plátano verde hartón por unidad',
    price: 800,
    unit: 'unidad',
    imageUrl: 'https://placehold.co/400x400/0a7e3a/white?text=Platano.webp',
    categoryId: 'cat-fv',
    inStock: true,
    is_variable_weight: false,
    currency: 'COP',
  },
  {
    id: 'tomate-chonto-1lb',
    name: 'Tomate chonto 1lb',
    name_display: 'Tomate Chonto',
    name_legal: 'Tomate chonto fresco 1 libra',
    price: 3200,
    unit: '1 lb',
    imageUrl: 'https://placehold.co/400x400/0a7e3a/white?text=Tomate.webp',
    categoryId: 'cat-fv',
    inStock: true,
    is_variable_weight: false,
    currency: 'COP',
  },
  {
    id: 'cebolla-cabezona',
    name: 'Cebolla cabezona blanca 1lb',
    name_display: 'Cebolla Cabezona',
    name_legal: 'Cebolla cabezona blanca fresca 1 libra',
    price: 2800,
    unit: '1 lb',
    imageUrl: 'https://placehold.co/400x400/0a7e3a/white?text=Cebolla.webp',
    categoryId: 'cat-fv',
    inStock: true,
    is_variable_weight: false,
    currency: 'COP',
  },
  {
    id: 'aguacate-hass',
    name: 'Aguacate Hass',
    name_display: 'Aguacate Hass',
    name_legal: 'Aguacate variedad Hass por unidad',
    price: 3500,
    unit: 'unidad',
    imageUrl: 'https://placehold.co/400x400/0a7e3a/white?text=Aguacate.webp',
    categoryId: 'cat-fv',
    inStock: true,
    is_variable_weight: false,
    currency: 'COP',
    badge: 'Oferta',
  },

  // ── Despensa (Abarrotes) ──────────────────────────────────────────────────
  {
    id: 'arroz-1kg',
    name: 'Arroz blanco 1kg',
    name_display: 'Arroz',
    name_legal: 'Arroz blanco pulido extra 1 kilogramo',
    price: 5500,
    unit: '1 kg',
    imageUrl: 'https://placehold.co/400x400/0a7e3a/white?text=Arroz.webp',
    categoryId: 'cat-ab',
    inStock: true,
    is_variable_weight: false,
    currency: 'COP',
  },
  {
    id: 'aceite-girasol-1l',
    name: 'Aceite de girasol 1L',
    name_display: 'Aceite Girasol',
    name_legal: 'Aceite vegetal de girasol refinado 1 litro',
    price: 12000,
    unit: '1 L',
    imageUrl: 'https://placehold.co/400x400/0a7e3a/white?text=Aceite.webp',
    categoryId: 'cat-ab',
    inStock: true,
    is_variable_weight: false,
    currency: 'COP',
  },
  {
    id: 'azucar-1kg',
    name: 'Azúcar blanca 1kg',
    name_display: 'Azúcar',
    name_legal: 'Azúcar blanca refinada 1 kilogramo',
    price: 4800,
    unit: '1 kg',
    imageUrl: 'https://placehold.co/400x400/0a7e3a/white?text=Azucar.webp',
    categoryId: 'cat-ab',
    inStock: true,
    is_variable_weight: false,
    currency: 'COP',
  },
  {
    id: 'panela-500g',
    name: 'Panela redonda 500g',
    name_display: 'Panela',
    name_legal: 'Panela de caña de azúcar redonda 500g',
    price: 3800,
    unit: '500 g',
    imageUrl: 'https://placehold.co/400x400/0a7e3a/white?text=Panela.webp',
    categoryId: 'cat-ab',
    inStock: true,
    is_variable_weight: false,
    currency: 'COP',
  },
]

// ─── Helpers ──────────────────────────────────────────────────────────────────

/** Productos disponibles para el carrusel "Lo que no puede faltar" */
export const mockFeaturedProducts = mockProducts.filter(p => p.inStock)

/** Productos por categoría */
export function getProductsByCategory(categoryId: string): Product[] {
  return mockProducts.filter(p => p.categoryId === categoryId && p.inStock)
}
