/**
 * Productos del catálogo real de Leche y Miel.
 * Fuente autoritativa consumida por PWA y admin.
 *
 * `imageUrl` usa rutas relativas al root del origin (`/product-images/*` cuando
 * el deploy sirve ambos apps bajo el mismo dominio). En dev, la PWA sobrescribe
 * `imageUrl` con imports locales desde `src/assets/products/*` vía un mapper;
 * el admin no renderiza estas imágenes en la UI operativa.
 *
 * Para editar el catálogo: sumar/quitar/ajustar entradas aquí y correr
 * `bash scripts/check-catalog-drift.sh` (o el reset demo del admin).
 */

import type { Product } from './types'

const PLACEHOLDER = (label: string, colors = '9ca3af/f9fafb') =>
  `https://placehold.co/400x400/${colors}?text=${encodeURIComponent(label)}`

export const sharedProducts: Product[] = [
  // ── Lácteos ───────────────────────────────────────────────────────────────
  {
    id: 'leche-entera-1l',
    name: 'Leche entera pasteurizada 1L',
    name_display: 'Leche Entera',
    name_legal: 'Leche entera pasteurizada UHT 1 litro',
    price: 4500,
    originalPrice: 5800,
    unit: '1 L',
    imageUrl: '/product-images/lacteos/leche.png',
    categoryId: 'cat-la',
    inStock: true,
    is_variable_weight: false,
    currency: 'COP',
    description: 'Leche entera pasteurizada de alta calidad. Ideal para toda la familia: rica en calcio, proteínas y vitaminas esenciales.',
    nutritionalInfo: { serving: 'Por 240ml', calories: 150, protein: '8g', fat: '8g', carbs: '12g', fiber: '0g' },
    availability: 'Disponible',
  },
  {
    id: 'queso-campesino-250g',
    name: 'Queso campesino fresco',
    name_display: 'Queso Campesino',
    name_legal: 'Queso campesino fresco artesanal',
    price: 7500,
    unit: 'Por Kilogramo',
    imageUrl: '/product-images/lacteos/queso-campesino.png',
    categoryId: 'cat-la',
    inStock: true,
    is_variable_weight: true,
    currency: 'COP',
    badge: 'Local',
    description: 'Queso fresco artesanal elaborado con leche local. Sin conservantes, con sabor auténtico de la región.',
    nutritionalInfo: { serving: 'Por 30g', calories: 90, protein: '6g', fat: '7g', carbs: '1g', fiber: '0g' },
    availability: 'Pocas unidades',
  },
  {
    id: 'yogurt-natural-1l',
    name: 'Yogurt natural 1L',
    name_display: 'Yogurt Natural',
    name_legal: 'Yogurt natural entero sin azúcar 1 litro',
    price: 8200,
    unit: '1 L',
    imageUrl: '/product-images/lacteos/yogurt.webp',
    categoryId: 'cat-la',
    inStock: true,
    is_variable_weight: false,
    currency: 'COP',
    description: 'Yogurt natural entero sin azúcar añadida. Con cultivos vivos activos que favorecen la digestión.',
    nutritionalInfo: { serving: 'Por 200g', calories: 120, protein: '6g', fat: '4g', carbs: '14g', fiber: '0g' },
    availability: 'Disponible',
  },

  // ── Despensa ──────────────────────────────────────────────────────────────
  {
    id: 'frijol-bola-roja-500g',
    name: 'Frijol bola roja 500g',
    name_display: 'Frijol Bola Roja',
    name_legal: 'Frijol bola roja seco 500 gramos',
    price: 4200,
    unit: '500 g',
    imageUrl: '/product-images/abarrotes/frijol.webp',
    categoryId: 'cat-dp',
    inStock: true,
    is_variable_weight: false,
    currency: 'COP',
    description: 'Frijol bola roja seco, seleccionado y limpio. Fuente natural de proteína vegetal y fibra.',
    nutritionalInfo: { serving: 'Por 100g (seco)', calories: 337, protein: '22g', fat: '1.2g', carbs: '60g', fiber: '15g' },
    availability: 'Disponible',
  },
  {
    id: 'lenteja-500g',
    name: 'Lenteja 500g',
    name_display: 'Lenteja',
    name_legal: 'Lenteja seca 500 gramos',
    price: 3800,
    unit: '500 g',
    imageUrl: PLACEHOLDER('Lenteja', '92400e/fef3c7'),
    categoryId: 'cat-dp',
    inStock: true,
    is_variable_weight: false,
    currency: 'COP',
  },
  {
    id: 'arroz-1kg',
    name: 'Arroz blanco 1kg',
    name_display: 'Arroz',
    name_legal: 'Arroz blanco pulido extra 1 kilogramo',
    price: 5500,
    originalPrice: 7000,
    unit: '1 kg',
    imageUrl: '/product-images/abarrotes/arroz.png',
    categoryId: 'cat-dp',
    inStock: true,
    is_variable_weight: false,
    currency: 'COP',
    description: 'Arroz blanco pulido extra, grano largo. Cocción suelta y sabor neutro, perfecto para acompañar cualquier plato.',
    nutritionalInfo: { serving: 'Por 100g (cocido)', calories: 130, protein: '2.7g', fat: '0.3g', carbs: '28g', fiber: '0.4g' },
    availability: 'Disponible',
  },
  {
    id: 'aceite-girasol-1l',
    name: 'Aceite de girasol 1L',
    name_display: 'Aceite Girasol',
    name_legal: 'Aceite vegetal de girasol refinado 1 litro',
    price: 12000,
    originalPrice: 15000,
    unit: '1 L',
    imageUrl: '/product-images/abarrotes/aceite-girasol.png',
    categoryId: 'cat-dp',
    inStock: true,
    is_variable_weight: false,
    currency: 'COP',
    description: 'Aceite de girasol refinado, bajo en grasas saturadas. Ideal para frituras y aderezos de ensaladas.',
    nutritionalInfo: { serving: 'Por 15ml', calories: 130, protein: '0g', fat: '14g', carbs: '0g', fiber: '0g' },
    availability: 'Disponible',
  },
  {
    id: 'azucar-1kg',
    name: 'Azúcar blanca 1kg',
    name_display: 'Azúcar',
    name_legal: 'Azúcar blanca refinada 1 kilogramo',
    price: 4800,
    unit: '1 kg',
    imageUrl: PLACEHOLDER('Azucar', 'f9fafb/374151'),
    categoryId: 'cat-dp',
    inStock: true,
    is_variable_weight: false,
    currency: 'COP',
  },
  {
    id: 'atun-lata-170g',
    name: 'Atún en agua 170g',
    name_display: 'Atún',
    name_legal: 'Atún aleta amarilla en agua 170 gramos',
    price: 5500,
    originalPrice: 6800,
    unit: '170 g',
    imageUrl: PLACEHOLDER('Atun', 'bfdbfe/1e3a8a'),
    categoryId: 'cat-dp',
    inStock: true,
    is_variable_weight: false,
    currency: 'COP',
    badge: 'Oferta',
  },

  // ── Congelados / Embutidos ────────────────────────────────────────────────
  {
    id: 'chorizo-250g',
    name: 'Chorizo casero 250g',
    name_display: 'Chorizo',
    name_legal: 'Chorizo de cerdo artesanal 250g',
    price: 9000,
    originalPrice: 11500,
    unit: '250 g',
    imageUrl: '/product-images/carnes/chorizo.webp',
    categoryId: 'cat-co',
    inStock: true,
    is_variable_weight: false,
    currency: 'COP',
  },
  {
    id: 'salchichas-viena-250g',
    name: 'Salchichas tipo viena 250g',
    name_display: 'Salchichas Viena',
    name_legal: 'Salchichas tipo viena de cerdo y res 250g',
    price: 7800,
    unit: '250 g',
    imageUrl: PLACEHOLDER('Salchichas', 'fca5a5/7f1d1d'),
    categoryId: 'cat-co',
    inStock: true,
    is_variable_weight: false,
    currency: 'COP',
  },

  // ── Bebidas ───────────────────────────────────────────────────────────────
  {
    id: 'gaseosa-cola-2l',
    name: 'Gaseosa cola 2L',
    name_display: 'Gaseosa Cola',
    name_legal: 'Bebida gaseosa sabor cola 2 litros',
    price: 6500,
    unit: '2 L',
    imageUrl: PLACEHOLDER('Gaseosa', 'dc2626/fff1f2'),
    categoryId: 'cat-be',
    inStock: true,
    is_variable_weight: false,
    currency: 'COP',
  },
  {
    id: 'agua-botella-600ml',
    name: 'Agua purificada 600ml',
    name_display: 'Agua Purificada',
    name_legal: 'Agua purificada en botella 600 mililitros',
    price: 2000,
    unit: '600 ml',
    imageUrl: PLACEHOLDER('Agua', 'e0f2fe/0c4a6e'),
    categoryId: 'cat-be',
    inStock: true,
    is_variable_weight: false,
    currency: 'COP',
  },

  // ── Limpieza ──────────────────────────────────────────────────────────────
  {
    id: 'detergente-1kg',
    name: 'Detergente en polvo 1kg',
    name_display: 'Detergente',
    name_legal: 'Detergente en polvo multiuso 1 kilogramo',
    price: 11500,
    originalPrice: 14000,
    unit: '1 kg',
    imageUrl: PLACEHOLDER('Detergente', '4f46e5/eef2ff'),
    categoryId: 'cat-as',
    inStock: true,
    is_variable_weight: false,
    currency: 'COP',
  },
  {
    id: 'jabon-bano-3pack',
    name: 'Jabón de baño x3 unidades',
    name_display: 'Jabón de Baño',
    name_legal: 'Jabón de baño en barra 3 unidades 100g c/u',
    price: 8500,
    unit: 'x3 und',
    imageUrl: PLACEHOLDER('Jabon', 'd1fae5/064e3b'),
    categoryId: 'cat-as',
    inStock: false,
    is_variable_weight: false,
    currency: 'COP',
  },

  // ── Electrodomésticos ─────────────────────────────────────────────────────
  {
    id: 'nevera-haceb-250l',
    name: 'Nevera 250L Haceb',
    name_display: 'Nevera 250L',
    name_legal: 'Refrigerador doméstico 250 litros marca Haceb',
    price: 1350000,
    originalPrice: 1650000,
    unit: 'unidad',
    imageUrl: PLACEHOLDER('Nevera', 'e2e8f0/1e293b'),
    categoryId: 'cat-el',
    inStock: true,
    is_variable_weight: false,
    currency: 'COP',
    badge: 'Oferta',
  },
]
